### ISSUE TITLE
(Release 0.7.2) To-do list

### ISSUE THREAD

**Issue by CatStark** [jina-ai/finetuner#682]
To release we need to close the next tickets:

- [x] https://github.com/jina-ai/finetuner/pull/679
- [x] https://github.com/jina-ai/finetuner/pull/678
- [x] https://github.com/jina-ai/finetuner-core/pull/488
- [x] https://github.com/jina-ai/finetuner/pull/684
- [ ] https://github.com/jina-ai/finetuner-core/pull/486 (Optional)
